### ISSUE TITLE
replace texts in a .vsdx-file

### ISSUE THREAD

**Issue by GearsChen** [dave-howard/vsdx#1]
Hi Mr. Howard,

could you please post a small example of replacing some text in a .vsdx-file?

For example, replacing the text "dog" in a square with "cat".

Best regards
GC

**Comment by dave-howard** [comment]
Hi GC - That's a sensible use case so I have added a find_replace() method to Page and Shape classes, as well as a new test showing how to use. Hopefully suits your needs,
Dave
