### ISSUE TITLE
nice project 

### ISSUE THREAD

**Issue by AronWaterAron** [dave-howard/vsdx#2]
I love using draw io very much,
however to export the graph,
the only support format that could preserve some information is vsdx,
but there are so few vsdx python libraries out there.

**Comment by dave-howard** [comment]
Hi - thank you, I am glad you like it. 
I saw and used docx and openpyxl and needed to also do some processing of vsdx files, couldn't find anything to do what I needed so decided to start this project. I hope you find this even a little bit as useful as I have the docx and openpyxl packages
