### ISSUE TITLE
Exporting attributes of shapes

### ISSUE THREAD

**Issue by frankhefner** [dave-howard/vsdx#20]
Hi,
I am quite new to this library. 
I do have the task to export the attributes of any shape from a Visio file. For now I do not have found any function within class vsdx.VisioFile.Shape that would allow looping over the attributes.

My code is as follows:

_from vsdx import VisioFile
with VisioFile('Test_Prozess_neu.vsdx') as vis:
    # open first page
    page = vis.get_page(0)
    # Read all shapes
    shapes = page.shapes[0].sub_shapes()
    # Loop over all available shapes
    for shape in shapes:
        print(shape.text)
        print(shape.ID)
        # Now I would normally execute the function for exporting all attributes...__

Do I do something wrong or does this function simply not exist (yet)?

Thanks for some support,
Frank

**Comment by dave-howard** [comment]
Hi Frank - always good to see people using this :)

Just want to check what sort of attributes you mean - i.e. `VisioFile.Shape` object fields/properties or attributes of the original shape in Visio.

For the `VIsioFIle.Shape` object you can list attributes using `shape.__dict__`

So something like `print(f"shape {shape.ID} {shape.__dict__}") in your loop`

You might notice the the `Shape.cells` property when you do that, which provides a list of many of the attributes within the original Visio shape as in truncated example below:

'cells': {'PinX': Cell: name=PinX val=4.133858135787355 func=None, 'PinY': Cell: name=PinY val=10.65551182326173 func=None, 'Width': Cell: name=Width val=2.165354297053872 func=None .... and so on

Some of these have dedicated properties for getting/setting, like x and y, but many do not.

I hope that helps

Regards
Dave

**Comment by frankhefner** [comment]
Hi Dave,
Thanks for the prompt reply!
I have tested the list attributes function shape.__dict__ but unfortunatelly it is not showing the attributes/data of the shapes I am trying to get.
I am searching for the data/attribute fields that I can view or define when I do a right click upon a shape, then choose "Data" -> "Shape Data" or "Data" -> "Define Shape Data".
Please see attached screen shot. And sorry for the german language ;-)
Any ideas how I can extract this kind of information from the Visio file?


Regards,
Frank

![Visio_Shape_Data](https://user-images.githubusercontent.com/87135951/126115529-8bda2b1b-8d05-4926-ae10-6700280d0150.jpg)

**Comment by dave-howard** [comment]
I see what you mean now - let me look into that

**Comment by dave-howard** [comment]
Hello Frank - I have just released v0.4.7, which introduces `ShapeProperty' class, a list of these being available from `Shape.data_properties` property. This is a basic initial implementation - it is lacking any specific consideration of master shape inheritence and of the value type (all values will be strings). You might want to look at the test method: `test_get_shape_data_properties()` for guidance.
I hope this helps with what you were trying to do,
Kind regards
Dave

**Comment by frankhefner** [comment]
Hi Dave,
sorry for coming back that late upon this.
I have installed the new version and looked into the mentioned test method. 

This is my code:
# process properties
shapeProps = shape.data_properties
                
# loop over the properties
for prop in shapeProps:
     print("Property value: " + str(prop.value))

The loop does at least provide the correct amount of properties, being set on a shape. 
But I do struggle with getting the property_name and property_value. The function prop.value always returns "None".

Would you have any advice for me, how to query the name and value of the property?
Does it have something to do with the dictionary that you are passing to the function as a parameter?

Thanks in advance.

Regards,
Frank

**Comment by dave-howard** [comment]
Hi Frank - looks like a bug in the library code (and test for this feature) rather than anything you are doing wrong. The fix is included in release v0.4.9 that I have just pushed here and to PyPI. I'll re-open this issue so we can close when properly resolved.

**Comment by dave-howard** [comment]
Hi Frank - just a heads up that I will change the Shape.data_properties type from list to dict in the next release, so just be aware of that. 
The reason for this is to make it easier to get a specific property from a shape e.g. `my_shape.data_properties['my_prop_name'].value`

**Comment by frankhefner** [comment]
Hi Dave,
Thanks for taking care and for the heads up.
I am going to test v0.4.9 next week.

Have a nice weekend,
Frank

**Comment by frankhefner** [comment]
Hi Dave,
I do have tested now v0.4.10. We are almost there but I would need a last information from you.
When iterating over the data properties with the following code, I do only get the last data property as output.

for key, dataProperty in shape.data_properties.items():
        print(dataProperty.__getattribute__('name'), '->', dataProperty.__getattribute__('value'))

Do I have to develop the loop differently or is the dictionary only having one item?


Regards,
Frank

**Comment by dave-howard** [comment]
Hi Frank - that code seems valid, it does loop through two data items in the test file.

If I add it to test `test_get_shape_data_properties()` it runs fine and adds the expected output lines below...

my_property_name -> property value
my_second_property_name -> another value

Note: The properties dict is indexed by label, not name - this is because the label is visible without opening the define data popup in Visio so it's a more convenient label for a shape - do your properties have labels?

it's unrelated, but you can also loop through as below:
```
for prop in shape.data_properties.values():
    print(prop.name, prop.value)
```

Dave

**Comment by frankhefner** [comment]
Hi Dave,
You are right, the code works perfect for all new defined data properties on a shape.
However, in my test file I have used a master shape that already had defined some data properties . If I enter some text to all data properties of the master shape, only the "last" one is being shown.

I would like to attach my test Visio file here, but github does not allow for uploading Visio files. So, I do only attach a screen-shot that shows the master shape and its data properties.
![Master_shape_data_properties](https://user-images.githubusercontent.com/87135951/133578358-551a3438-02b5-4d69-8d5e-1090c11202a0.png)


If I loop through the data properties of the master shape "shape.master_shape.items()" then I do get all data properties, but not the values.
Would you have another hint for me, how to get all values of any data property of the master shape?


Ciao,
Frank

**Comment by dave-howard** [comment]
That makes complete sense now :)
I didn't take account of master shape properties - I've updated and release v0.4.11 and hopefully this will now work as expected.

Thanks
Dave

**Comment by frankhefner** [comment]
Hi Dave,
I have installed release v0.4.11 and tested it with my Visio test file. The result is still the same:

![Shape_properties_v_0_4_11](https://user-images.githubusercontent.com/87135951/134148303-ecf724c7-15ed-47e9-86bf-d1d36fbaa9ac.png)

When looking at the list of the shape properties it is showing all properties from the master shape and then it is repeating the last property having a value set. In my case the last property with a value is "Status".

Any further ideas from your side?


Cheers,
Frank

**Comment by dave-howard** [comment]
Hi Frank - the properties are indexed by the label, so if the master and shape both have a property with label 'label1' the shape property should override the master shape property with same label. I suspect that is what is happening here..

There should only be on property with label of 'Status' - but I guess that is the name not the label?

The output of on the right is really helpful, if you could add **label, name, value, and shape.ID** to that list it might help clarify what is going on.

Also - it looks like some values it is returning are incorrect based on the screenshot - I would have expected to see 'Staging', 'FHe' etc in there

Thanks
Dave

**Comment by frankhefner** [comment]
Hi Dave,
good news, now it is working perfectly!
![Shape_properties_v_0_4_13_working_perfect](https://user-images.githubusercontent.com/87135951/134863062-8acfaf01-310f-4e3a-964d-209ea8da1dbf.png)

Thanks for all of your efforts and support!


Have a great week,
Frank

**Comment by dave-howard** [comment]
Great news, took a few attempts but learned a bit along the way so always worthwhile :)

Thanks for comfirming so quick Frank

Cheers
Dave
