### ISSUE TITLE
Cannot open in Lucid

### ISSUE THREAD

**Issue by edurguti** [dave-howard/vsdx#35]
Hi, I am editing a visio file created in lucid.app, I am just replacing some text and then adding it back to lucid.app but it won't open it.

![image](https://user-images.githubusercontent.com/19334167/150424865-fbef8624-6690-4bf4-8ddb-8487f0f5e92e.png)

**Comment by dave-howard** [comment]
H @edurguti - just a quick note to let you know I have seen this issue.
I am not a Lucid user - but having signed up to check this issue,, I can confirm I see the same issue with the test case files. Input file can be imported into Lucid, output file can't be imported. 
No idea at this point why not - but of course ideally you should be able to import into Lucid. I would expect there is something missing or changed in the output file which Visio itself resolves when opening, but is nonetheless incorrect.
I can't promise any speedy resolution to this, or even any resolution at this point, but I will look into what the issue might be - and of course welcome any one else picking this issue up
Kind regards
Dave

**Comment by edurguti** [comment]
@dave-howard  thank you for your answer, it is not critical at this point. I am the only user in my team using Lucid, so this isn't a big issue as it works fine on MS Visio.

**Comment by dave-howard** [comment]
@edurguti Hi - I have just released v0.4.17, and this has resolved the problem for me, at least a couple of files that were failing previously I can now import into Lucid after the change. 
The issue seemed to have been one related to xml namespaces - though I can see the output files do still differ in some ways to those created by Visio so some isues may remain.

Please let me know if upgrading resolves the issues you were seeing,

KInd regards
Dave

**Comment by edurguti** [comment]
@dave-howard  I confirmed this is is working. Thank you! There are small issues with rendering but 99% is fine!
