### ISSUE TITLE
Retrieve the BaseID of a Shape's Masters XML part

### ISSUE THREAD

**Issue by jmgarcia-iriusrisk** [dave-howard/vsdx#44]
Hi @dave-howard, first to all, I would like to say thanks for this library, it became very helpful in our daily tasks.
We are trying to difference between shapes that has the same master name, as we can see, the only way to do that is to use the BaseID from [Masters XML Part](https://docs.microsoft.com/en-us/openspecs/sharepoint_protocols/ms-vsdx/e58f5f25-76d8-4f65-ae24-d286b10168d7) but the library doesn't expose that attribute, could be posible to update it with that new attribute?

Thanks for your great work.
Kind regards,
Juan.

**Comment by dave-howard** [comment]
HI @jmgarcia-iriusrisk  - I've added a master_base_id property to Page class now,

Kind regards
Dave

**Comment by jmgarcia-iriusrisk** [comment]
Hi @dave-howard, thanks for your fast reply. 
Could it be possible to retrieve the UniqueID of the Master too?
As we've seen with the AWS Stencils response in Visio,
![image](https://user-images.githubusercontent.com/108399255/178245316-35f20ee2-936c-4dfd-a160-a0ae783ef5ed.png)

that seems to be the identifier:
![image](https://user-images.githubusercontent.com/108399255/178245648-bf224da8-d375-40e5-b352-98f234bb38c6.png)

Thanks for your great work.
Kind regards,
Juan.

**Comment by dave-howard** [comment]
Hi @jmgarcia-iriusrisk  - I'll add this property in next release

**Comment by dave-howard** [comment]
Done `Page.master_unique_id` property added in v0.5.9
