### ISSUE TITLE
Question about missing attributes

### ISSUE THREAD

**Issue by arac-codespace** [dave-howard/vsdx#49]
Hi,

I'm currently trying to extract some location information for each shape in a visio file.  However, I noticed that sometimes these attributes are not mapped to the Shape class and they aren't in the page's xml either.  

Is it normal for certain attributes to not appear in the XML at all?  For example, I'm trying to detect when a shape is rotated by 90 degrees.  The visio file has some default 'System' shapes and I want to get the rotated shape created by that default quick shape in addition to any other that are at an angle.  That angle attribute is not shown anywhere though.  

XML:
![image](https://user-images.githubusercontent.com/23745004/181521045-f8cad777-6b6f-4d09-86af-5faf13f8d465.png)

And this is what I see in the debugger:
![image](https://user-images.githubusercontent.com/23745004/181522901-dcdd973d-ea57-4b6c-aa73-6c28aa994d2c.png)

**Comment by dave-howard** [comment]
Hi @arac-codespace - I have done a simple test by rotating some shapes and checking what that does to shape XML, What I see is an Angle Cell element within the shape xml.
I have added a Shape.angle property to make it easy to access this - this will be in v0.5.10
I notice your shape above has a mastershape - I wonder if the master shape is where the angle property is

**Comment by arac-codespace** [comment]
Thanks @dave-howard 

I made a similar test and found the same Angle cell.  My initial assumption was that quick shapes have default attributes stored somewhere, and those attributes are not shown in the shape's XML if they are not modified (so the program falls back to using the predefined defaults).

I didn't think of looking for those definitions elsewhere.  I'll take a look next week and see if those properties are defined in the master shape or elsewhere.  Hopefully they are.
