### ISSUE TITLE
copy_shape() not working as expected - shape not duplicated

### ISSUE THREAD

**Issue by stevensultana** [dave-howard/vsdx#5]
Hello, thank you for this project!
Any tips on how copy_shape() method can be used?

**Comment by stevensultana** [comment]
Hmm, I think I hacked together a half-baked solution.

It seems like `VisioFile.get_shapes()` is never called, so `set_new_id()` does not have anything in `page_max_ids` to increment, thus the new shape has the same ID as the source shape.

My solution was to call `VisioFile.get_shapes()` in `VisioFile.open_vsdx_file()` like this:

```
        self.pages = self.load_pages()
        
        for page in self.page_objects:
            self.get_shapes(page.filename)

        return self.pages
```

**Comment by dave-howard** [comment]
Hello - thanks for reminding me :) I started the copy method but did not complete. I will do that and add a related test. Looks like your solution above is exactly what is missing, but I will also add the copy method to Shape object for ease of use.

**Comment by dave-howard** [comment]
Hello - just pushed a change with two new tests related to this, seems to have resolved. Shape ID not changing was actually an issue in copy_shape() method incrementing source shape instead of new shape. Shape class now has a copy() method.

**Comment by stevensultana** [comment]
Hello Dave, thanks for the update!
I think there is still a problem, however. From the tests themselves, the output file does not have the new shape visible.
Looking into it, there is the definition of the shape in the xml. Eg. for test1.vsdx, there are 5 shapes listed and the fifth shape is in fact a copy of the source shape.
However, that copied 5th shape's ID is 1, whereas it should be ID 7 (the next ID in the page).

I suspect that problem happens because the get_shapes() method is never called, which goes through the shapes in a page and determines the current largest ID, which is then used by the copy methods.

**Comment by dave-howard** [comment]
Hello - thank you for testing, and yes you are right. I'll get that resolved in next release and add a note here when that's done.

**Comment by dave-howard** [comment]
Hi Steven - closing this after after your changes merged to resolve. Thanks for your help
