### ISSUE TITLE
shape: is_master_shape(self) incorrect

### ISSUE THREAD

**Issue by kempeng** [dave-howard/vsdx#66]
the function is_master_shape(self) as part of the Shape class is not working correctly, the issues seems to be with the function 

 def is_master_page(self):
        return type(self.vis.masters_xml)==ET.Element and self.vis.masters_xml.find(f'{namespace}Master[@ID="{self.page_id}"]/{namespace}PageSheet') is not None

in the Page class: it uses the Page ID to test wether a Master exists with the same ID.

I don't think that a page ID and a master ID share the same ID "space" and are unique between them. I am working on a VSDX file in which a Page and a Master have the same ID value.

**Comment by dave-howard** [comment]
Hi @kempeng  - you are right, this method appers to be incorrect (it is only referenced in `Shape.__repr__()` within the package). I will take a look, hoepfully be able to resolve and add some tests to validate.
Thanks for raising the issue

**Comment by dave-howard** [comment]
@kempeng  - this should be resolved in __v0.5.19__
